def main():
    """Establece la programacion de distintos canales y extrae la programacion de Caracol
"""
    from bs4 import BeautifulSoup
    from urllib.request import urlopen
    
    #Descripciones y Horarios De los Programas Variantes
    
    General_Canal_Dic={}

    ListaCar={}
    ListaCar["En otra piel"]=['Novela', 'Dos mujeres completamente diferentes, pero que comparten un mismo destino trágico, se verán unidas después de la muerte. Una historia de misterio, amor y venganza, en la que dos almas ocuparán un mismo cuerpo para buscar justicia.']
    ListaCar["También Caerás"]=['Entretenimiento', 'Este programa de humor es un espacio abierto a la alegría y la espontaneidad, que lleva las cámaras escondidas a otro nivel. La gente común y corriente se convierte en protagonista de situaciones divertidas, inusuales y hasta aterrorizantes.']
    ListaCar["Pedro el escamoso"]=['Novela', 'Un hombre llega a la ciudad en busca de un mejor futuro, trabaja como chofer en una empresa y se enamora de la secretaria de su jefe.']
    ListaCar["La finca de hoy"]=['Informativo', 'La Finca de Hoy es el programa agropecuario de Caracol Televisión,  donde se muestran mejoras tecnológicas y progresos que se pueden aplicar al campo.']
    ListaCar["Día a día"]=[ 'Entretenimiento', 'Día a Día es un programa magazín matutino de la televisión colombiana, producido y emitido por Caracol Televisión. Es presentado por Catalina Gómez, Carolina Cruz, Carolina Soto y el presentador Carlos Calero. También interviene Alberto José Linero.']
    ListaCar["Noticias Caracol"]=['Informativo', 'Edición central del noticiero informativo que registra todos los días de la semana los hechos más importantes de Colombia y el mundo, en los campos de entretenimiento, deportes, salud, arte y muchas más.']
    ListaCar["Cuentos de los Hermanos Grimm"]=['Infantil', 'Una narración de los célebres cuentos clásicos infantiles de los hermanos Grimm.']
    ListaCar["La red"]=['Entretenimiento', 'Programa de entretenimiento y farándula colombiano de Caracol. Su formato es "variado", pues se combinan noticias de espectáculos, entrevistas, concursos, críticas de la farándula colombiana.']
    ListaCar["Se Dice De Mí"]=['Entretenimiento', 'Un programa que muestra la historia de vida y trayectoria de cantantes, deportistas, actores y presentadores, donde hablan sobre los aspectos positivos y negativos de sus vidas.']
    ListaCar["Sábados Felices"]=['Comedia', 'Programa humorístico de la televisión colombiana donde se presentan comediantes y distintos tipos de humoristas.']
    ListaCar["Expediente Final"]=['Entretenimiento', 'Un programa que saca a la luz los secretos de las muertes de las celebridades de Colombia, porque no todo lo investigado es revelado.']
    ListaCar["The Suso's Show"]=['Comedia', 'Un programa de comedia y talk show en donde "Suso el Paspi" hablará con personajes famosos sobre diversos temas.']
    ListaCar["Un refugio para el amor"]=['Novela', 'Una historia de amor intenso entre una joven hermosa y humilde y un galán adinerado, que tiene la fama de ser un gran conquistador y las dificultades que tendrán que atravesar para estar juntos.']
    ListaCar["Mi marido tiene familia"]=['Novela','Julieta y su esposo son muy felices, pero una jugada del destino los pone en una situación difícil y cómica: sus suegros, que ellos pensaban que vivían en el extranjero, resultan ser los nuevos dueños de la propiedad que alquilan.']
    ListaCar["Bella Calamidades"]=['Novela','Lola, una joven que vive marcada por la desgracia y la mala suerte y un hombre que nunca ha podido olvidarla desde que la conoció en su niñez, que a pesar del tiempo transcurrido sueña con reencontrarse con ella.']
    ListaCar["Pasión de Gavilanes"]=['Novela', 'Los hermanos Reyes, quienes buscan vengar la muerte de su hermana, se instalan como trabajadores en la hacienda de la familia Elizondo. El odio que sienten los hermanos pronto comienza a disiparse cuando se enamoran de las hermanas Elizondo.']
    ListaCar["Séptimo Día"]=['Informativo', 'Un programa periodístico que trata temas de actualidad controversiales. Se habla sobre temas polémicos como problemas sociales, económicos, educativos y más en Colombia.']
    ListaCar["Preso N° 1"]=['Novela', 'Carmelo Alvarado proviene de una familia campesina en el norte de México. Gracias a su carácter e inteligencia, él comienza a trabajar en televisión y pronto se convierte en líder de opinión. Más tarde, es candidato a presidente. Ya en el gobierno, Carmelo enfrenta dos grupos de presión: el Impala y los narcos. Pero una falsa acusación en su contra lo lleva a prisión. Se hace más popular, pero más peligroso para sus enemigos, quienes deciden asesinarlo tras las rejas.']
    ListaCar["En otra piel"]=['Novela', 'Dos mujeres completamente diferentes, pero que comparten un mismo destino trágico, se verán unidas después de la muerte. Una historia de misterio, amor y venganza, en la que dos almas ocuparán un mismo cuerpo para buscar justicia.']
    ListaCar["Entre ojos"]=['Informativo', 'Un espacio que profundiza en diversos personajes y hechos reales, para hacerlos públicos y trascendentes a partir de entrevistas, reportajes y material documental.']
    ListaCar["Los Informantes"]=['Informativo', 'Los informantes es un programa de televisión colombiano, realizado por Caracol Televisión, es conducido por María Elvira Arango y transmitido todos los domingos a las 8:00pm después de Noticias Caracol.']
    ProgramasCaracolDeleteados=["Pura diversión", "Santa misa", "Titanes Caracol","Voy por ti, juega por mi","Expediente Final","Angelus desde el vaticano","Noches de premier","Noticiero del senado","Especiales Caracol", "Doble vía", "Puro cine", "El mundo visto desde el vaticano","Contagiémonos de Solidaridad","Imperio de mentiras","Lo que la vida me robó" ]

    Dicc_Fox = {}
    Dicc_Fox['Los Simpson'] = ['Lunes, Martes, Miércoles, Jueves, Viernes', '12:01 PM - 12:49 PM', 'Entretenimiento', 'En Springfield, los Simpson, una familia de clase trabajadora compuesta por Marge, Homero, Bart, Lisa y Maggie, vive aventuras satíricas.']
    Dicc_Fox['Si decido quedarme']=['Lunes', '02:05 PM - 03:54 PM', 'Pelicula', 'Después de que un accidente automovilístico la deja entre la vida y la muerte, una adolescente enfrenta una decisión que determinará su destino final.']
    Dicc_Fox['Oblivion: el tiempo del olvido']=['Lunes', '03:55 PM - 06:00 PM', 'Pelicula', 'Jack Harper y Victoria Olsen son los únicos habitantes de la Tierra, destruida hace sesenta años. Harper, un mecánico de aviación, rescata a una mujer antes de abandonar la Tierra para siempre e inicia una batalla para salvar a la humanidad.']
    Dicc_Fox['Hancock']=['Lunes', '06:09 PM - 07:45 PM', 'Pelicula', 'Un superhéroe bastante impopular protege a los ciudadanos de Los Ángeles, pero provoca grandes daños colaterales después de cada acto heroico que realiza.']
    Dicc_Fox['Futurama']=['Lunes, Martes, Miércoles, Jueves, Viernes', '07:50 PM - 08:10 PM', 'Entretenimiento', 'Accidentalmente, Fry, un repartidor de pizza congelada, se despierta 1000 años en el futuro. Él es recibido por su único descendiente, un científico anciano y débil que es dueño de un servicio de despacho de carga.']
    Dicc_Fox['Miedo profundo']=['Lunes', '01:13 AM - 02:25 AM', 'Pelicula', 'Una joven que practicaba surf en una solitaria playa mexicana queda atrapada en un islote a solo cien metros de la costa. La distancia es corta, pero un enorme tiburón blanco se interpone entre ella y la otra orilla.']
    Dicc_Fox['Los juegos del hambre en llamas']=['Lunes', '04:05 AM - 06:31 AM', 'Pelicula', 'Tras salir victoriosos en los juegos del hambre, Katniss Everdeen y Peeta Mellark emprenden el tour de la victoria. Katniss cree que se está gestando una rebelión, pero un cruel cambio en las reglas del próximo torneo podría cambiar Panem.']
    Dicc_Fox['Como entrenar a tu dragón']=['Martes', '05:57 PM - 07:36 PM', 'Pelicula', 'Hipo, un vikingo adolescente, comienza las clases de entrenamiento con dragones y ve por fin una oportunidad para demostrar que es capaz de convertirse en guerrero cuando hace amistad con un dragón herido.']
    Dicc_Fox['Logan']=['Martes, Miércoles','10:00 PM - 12:31 AM', 'Pelicula', 'Sin sus poderes, por primera vez, Wolverine es verdaderamente vulnerable. Después de una vida de dolor y angustia, sin rumbo y perdido en el mundo donde los X-Men son leyenda, su mentor Charles Xavier lo convence de asumir una última misión: proteger a una joven que será la única esperanza para la raza mutante.']
    Dicc_Fox['Actos de violencia']=['Martes','01:15 AM - 02:44 AM', 'Pelicula', 'Cuando su novia es secuestrada por traficantes de personas, Roman y sus ex hermanos militares se dispusieron a localizarla y salvarla antes de que sea demasiado tarde. En el camino, Roman se une a Avery, un policía que investiga la trata de personas y lucha contra la burocracia corrupta que tiene intenciones dañinas.']
    Dicc_Fox['Tres divas y una agente']=['Martes', '04:05 AM - 05:34 AM', 'Pelicula', 'Los ejecutivos de una cadena de televisión pretenden reunir a tres legendarias estrellas en un concierto de sólo una noche, el único obstáculo es que ellas se odian mutuamente. Para ello, Wesley, hijo adoptivo de Kate y productor del especial, acude a la única persona que cree capaz de unir a las tres divas: La agente Beryl Mason.']
    Dicc_Fox['Speechless']=['Martes, Miércoles, Sábado, Domingo', '05:55 AM - 06:17 AM', 'Entretenimiento', 'Maya le da una mano a Melanie, y nota que su vida está dando un giro sorprendente. Dylan se une al equipo de baloncesto de Lafayette, donde su nula deportividad da sus resultados, y Jimmy compensa el tiempo perdido de padre e hijo con Ray.' ]
    Dicc_Fox['Will and Grace']=['Miércoles, Jueves, Viernes, Sábado', '06:17 AM - 06:38 AM', 'Entretenimiento', 'Will y Grace creen que Karen corre peligro cuando su novio Phil la lleva a una cabaña en el bosque. Entonces, junto a la asistente de Karen, Friday, corren para salvarla. Por otro lado, Jack le cuenta una historia a un reportero para beneficiar a su bar.']
    Dicc_Fox['Los Aliens se comieron mi tarea']=['Miércoles', '10:29 AM - 12:10 PM', 'Pelicula', 'Rod y Elspeth son dos niños cuyo proyecto de ciencias es destruido cuando una nave espacial vuela por la ventana y aterriza sobre él. Lo que ellos no esperan es conocer a un grupo de amistosos alienígenas y a una planta que habla que están en busca de un malvado criminal. De repente, los chicos se encontrarán ayudando a la Policía Galáctica a derrotar a un alienígena que se hace pasar por humano y así salvar el mundo de un gran desastre.']
    Dicc_Fox['Life in pieces']=['Lunes, Miércoles, Jueves, Viernes', '02:13 PM - 03:00 PM', 'Entretenimiento', 'Tras sufrir un ataque al corazón, Tim se vuelve muy dependiente y molesta a toda la familia. Greg y Jen mantienen en secreto el género de su bebé, la mascota de Sophia resulta ser una rana peligrosa, y Matt y Colleen reciben noticias sobre su adopción.']
    Dicc_Fox['La verdad duele']=['Miércoles', '03:00 PM - 05:16 PM', 'Pelicula', 'El consumado neuropatólogo Dr. Bennet Omalu descubre las verdaderas causas de ETC, una enfermedad común en jugadores de fútbol americano que sufren frecuentes golpes en la cabeza durante los partidos. La búsqueda del Dr. Omalu por revelar la verdad al público lo pone en una peligrosa situación contra una de las instituciones más poderosas -y amadas- del mundo. Will Smith fue nominado a un Globo De Oro a Mejor Actor por este filme.']
    Dicc_Fox['Shrek tercero']=['Miércoles', '10:00 PM - 11:43 PM', 'Pelicula', 'Cuando Shrek se casó con Fiona, lo último que se imaginó es que podría convertirse en el siguiente rey. Pero cuando su suegro, el rey Harold, muere sin previo aviso, es exactamente lo que le espera. Y si Shrek, con la valiosa ayuda de Asno y del Gato con Botas, no encuentra un rey adecuado para el Reino de Muy Muy Lejano, el ogro tendrá que sentarse en el trono. Artie, el primo de Fiona, un vago nato que sigue en el instituto, es el candidato más prometedor, pero acaba siendo un auténtico reto para los tres.']
    Dicc_Fox['Amor y disfunción']=['Miércoles', '12:26 AM - 01:44 AM', 'Pelicula', 'La vida de Zoe Crandle no salió exactamente como ella planeaba. Su negocio está fallando y se resigna a una vida de una sola noche. Justo cuando parece que todo su mundo se está desmoronando, se encuentra con Paul, un compañero adorable con quien tiene una conexión instantánea. Solo hay un problema, Paul está casado.']
    Dicc_Fox['Dúplex']=['Miércoles', '01:44 AM - 03:07 AM', 'Pelicula', 'Alex y Nancy son una joven y dinámica pareja con un futuro prometedor. Nancy trabaja para una prestigiosa revista, y Alex escribe su segundo libro; y lo que es más importante, se tienen el uno al otro. Sin embargo, hay algo de lo que no disponen: un hogar propio. Un buen día un agente inmobiliario los lleva a Brooklyn, donde dan con la casa de sus sueños: un encantador dúplex de los de antes, idóneo para ellos. Sin embargo, el nuevo hogar presenta una particularidad que no se esperan: en el piso superior vive una peculiar inquilina de antigua renta fija, la Sra. Connelly.']
    Dicc_Fox['Spider-Man: lejos de casa']=['Miércoles', '04:47 AM - 06:15 AM', 'Pelicula', 'Peter Parker decide pasar unas merecidas vacaciones en Europa junto a MJ, Ned y el resto de sus amigos. Sin embargo, Peter debe volver a ponerse el traje de Spider-Man cuando Nick Fury le encomienda una nueva misión: frenar el ataque de unas criaturas que están causando el caos en el continente.']
    Dicc_Fox['Sonido de la Navidad']=['Jueves', '10:00 AM - 11:59 AM', 'Pelicula', 'Lizzie, una joven maestra de piano, ayuda a la hija adolescente de Brad a aprender música. A medida que comienza a conocer a la chica, las chispas comienzan a volar con el padre, pero se sorprende al descubrir que él quiere comprar la escuela.']
    Dicc_Fox['Mentes poderosas']=['Jueves', '02:30 PM - 04:19 PM', 'Pelicula', 'Algo ha cambiado en Ruby. Puede que haya sobrevivido a la enfermedad que acabó con la vida de muchos niños pero, tanto ella como otros, han sufrido una consecuencia aún peor: tienen escalofriantes poderes que no pueden controlar.' ]
    Dicc_Fox['Megamente']=['Jueves', '04:19 PM - 06:05 PM', 'Pelicula', 'Megamente es el supervillano más brillante que el mundo haya conocido... y también el menos exitoso. Durante muchos años, ha buscado de todas las formas posibles conquistar Metro City. Sin embargo, cada uno de sus intentos se vio frustrado por culpa de Metro Man, un poderoso superhéroe. Pero, un día, Megamente consigue derrotar a su archienemigo y su vida comienza a carecer de sentido, por lo que decide crear a Titán, un nuevo héroe más fuerte que Metro Man. Los problemas comenzarán cuando Titán descubra que es más divertido ser malo que ser bueno. Ahora, Megamente deberá derrotar a su diabólica creación antes de que acabe con el mundo.']
    Dicc_Fox['Transformers: El último caballero']=['Jueves','10:00 PM - 12:52 AM', 'Pelicula', 'Humanos y Transformers están en guerra y Optimus Prime se ha ido. La clave para asegurar la subsistencia de la humanidad está en la historia oculta de los Transformers en la Tierra. Cade Yeager se unirá a un Lord inglés y a una profesora de la Universidad de Oxford para salvar al planeta Tierra. Al final de la batalla, sólo un bando sobrevivirá.']
    Dicc_Fox['Secuestro']=['Jueves', '01:35 AM - 03:06 AM', 'Pelicula', 'Una típica tarde en el parque se convierte en una pesadilla para la madre soltera Karla Dyson cuando su hijo de repente desaparece. Sin un teléfono celular y sabiendo que no tiene tiempo para esperar a la policía, la desesperada mujer inicia una persecución a los secuestradores y no se detendrá hasta salvar a su pequeño.']
    Dicc_Fox['Feliz día de tu muerte']=['Jueves', '03:06 AM - 04:37 AM', 'Pelicula', 'Una estudiante universitaria debe revivir el día de su asesinato una y otra vez, en un ciclo que terminará solo cuando descubra la identidad de su asesino.']
    Dicc_Fox['Mune: el guardián de la luna']=['Viernes', '04:15 PM - 05:50 PM', 'Pelicula', 'En un mítico mundo, un joven fauno, Mune, se convierte en guardián de la Luna en contra de sus propios deseos. Apenas preparado para el trabajo, Mune es respaldado por dos guardianes para detener una oscura amenaza que quiere controlar al sol.']
    Dicc_Fox['Vecinos cercanos del 3er tipo']=['Viernes', '05:50 PM - 07:43 PM', 'Pelicula', 'Para salir de sus rutinas diarias, un grupo de cuatro amigos se convierten en vigilantes de su barrio. A través de descabelladas aventuras, salvarán al mundo de una invasión extraterrestre. Uno de los alienígenas decide ayudar a la humanidad.']
    Dicc_Fox['Despicable me: minion madness']=['Viernes', '10:00 PM - 10:12 PM', 'Pelicula', 'Tres súbditos recién clonados pasan por el proceso de orientación en los laboratorios malvados de Gru. Por otro lado, los secuaces ayudan a renovar el hogar cuando descubren que un trabajador social los visitará y, además, un minion encuentra un plátano en su bolsa de almuerzo.']
    Dicc_Fox['Emoji: la película']=['Viernes', '10:12 PM - 11:51 PM', 'Pelicula', 'Dentro de la aplicación de mensajería, se encuentra Textopolis, una ciudad bulliciosa en la que viven todos los emojis, con la esperanza de ser seleccionados por el usuario del teléfono. En este mundo, cada emoji tiene solo una expresión facial, a excepción de Gene, un emoji exuberante que nació sin filtro y rebosa de múltiples expresiones. Decidido a convertirse en "normal" como los otros emojis, Gene recurre a la ayuda de su práctico mejor amigo Hi-5 y del famoso emoji rompecorazones Jailbreak. Juntos se embarcan en una épica aventura a través de las aplicaciones en el teléfono, cada uno de su propio mundo salvaje y divertido, para encontrar el Código que puede arreglar a Gene. Pero cuando un peligro mayor amenaza al teléfono, el destino de todos los emojis depende de estos tres amigos improbables que deben salvar su mundo antes de que se elimine para siempre.']
    Dicc_Fox['Maze Runner: La cura mortal']=['Viernes', '12:35 AM - 02:58 AM', 'Pelicula', 'Junto a su grupo de Gladers, Thomas debe entrar en la legendaria Last City, el laberinto más mortífero de todos, que es manejado por la organización CRUEL, la cual asegura haber encontrado la cura para la Lllamarada. Quien consiga salir de ahí con vida conocerá las respuestas a las preguntas que los Gladers se han estado haciendo desde que llegaron por primera vez al laberinto.']
    Dicc_Fox['Votos de amor']=['Viernes', '02:02 PM - 04:03 PM', 'Pelicula', 'Después de que su esposa despierta de un estado de coma con amnesia, un hombre intenta hacer que recupere su memoria y recuperar su relación.']
    Dicc_Fox['Deadpool 2']=['Sábado', '05:50 PM - 08:00 PM', 'Pelicula', 'Wade Wilson, mejor conocido como Deadpool, su nombre de batalla e identidad antiheroica, está de regreso con una nueva misión: salvar a un chico llamado Russell de las manos de un poderoso rival, Cable. En aras de dar cumplimiento a su tarea, el antihéroe formará un grupo, el X-Force.']
    Dicc_Fox['Misión: Imposible - Repercusión']=['Sábado', '10:00 PM - 12:45 AM', 'Pelicula', 'Ethan Hunt y su equipo IMF, acompañados por algunos aliados conocidos, deberán encarnar una lucha contrarreloj después de que una de sus misiones no salga como esperaban.']
    Dicc_Fox['Búsqueda implacable 3']=['Sábado', '10:00 PM - 12:06 AM', 'Pelicula', 'La esperada reconciliación del ex agente encubierto Bryan Mills con su ex esposa se ve trágicamente truncada por su brutal asesinato. Consumido por la ira, y culpado por el crimen, Mills se da a la fuga para evadir la implacable persecución de la CIA, el FBI y la policía. Por última vez, deberá hacer uso de su particular conjunto de habilidades para localizar a los verdaderos asesinos, impartir su característica justicia, y proteger lo único que le importa ahora: su hija.']
    Dicc_Fox['Falsa evidencia']=['Sábado', '04:34 AM - 06:12 AM', 'Pelicula', 'Evan Birch es un hombre de familia y un profesor querido en la universidad, donde su clase de filosofía es popular. Cuando una joven estudiante desaparece, los escarceos de Evan fuera del campus hacen que su mujer sospeche de él. El detective Malloy suma razones para dudar de Evan cuando encuentra pruebas que le convierten en el principal sospechoso.']
    Dicc_Fox['¡Esto es guerra!']=['Domingo', '12:28 PM - 02:15 PM', 'Pelicula', 'Dos agentes de la CIA y mejores amigos, Franklin FDR Foster y Tuck Hansen, son desplegados en Hong Kong para evitar que el criminal internacional Karl Heinrich adquiera un arma de destrucción masiva, pero la misión sale mal, resultando en la muerte del hermano de Heinrich, Jonas. Heinrich jura venganza contra ellos. Al regresar a América, su jefa, Collins, les asigna el trabajo de oficina para su protección. FDR es un mujeriego, que se hace pasar por capitán de un crucero, mientras que Tuck, que se presenta como agente de viajes, tiene una ex esposa, Katie y un hijo joven, Joe, quien cree que su papá es un debilucho. Luego de ver un comercial de citas por internet, Tuck decide inscribirse y es emparejado con Lauren Scott, una ejecutiva de pruebas de producto Poco tiempo después, FDR encuentra a Lauren en una tienda videos e intenta seducirla, sin saber que es la cita de Tuck. Ella supone que él es un mujeriego y lo ignora. Intrigado, FDR se entromete en uno de los grupos de prueba de Lauren y la convence para ir a una cita con él. A partir de ese momento, los dos agentes harán todo lo que esté en sus manos por destruirse mutuamente con tal de conseguir quedarse con la chica.']
    Dicc_Fox['Bohemian Rhapsody: La historia de Freddie Mercury']=['Domingo', '05:06 PM - 07:47 PM', 'Pelicula', 'Una celebración de Queen, su música y su extraordinario cantante Freddie Mercury, quien desafió los estereotipos y rompió la convención para convertirse en uno de los artistas más queridos del planeta. Además, desarrolla la creación de la banda que, a través de sus hits y su revolucionario sonido, logró alcanzar la fama mundial para convertirse en uno de los grupos más icónicos de todos los tiempos.']
    Dicc_Fox['Rápidos y Furiosos 7']=['Domingo', '10:00 PM - 12:09 PM', 'Pelicula', 'Ha pasado un año desde que el equipo de Dominic Torreto y Brian pudiera regresar finalmente a Estados Unidos, tras ser indultados. Desean adaptarse a una vida en la legalidad, pero el entorno ya no es el mismo. Dom intenta acercarse a Letty, y Brian lucha para acostumbrarse a la vida en una urbanización con Mia y su hijo. Ninguno de ellos imagina que un frío asesino británico, entrenado para realizar operaciones secretas, se cruzará en sus vidas para convertirse en su mayor enemigo.']
    Dicc_Fox['Comando especial']=['Domingo', '05:58 PM - 08:00 PM', 'Pelicula', 'Dos policías jóvenes se infiltran en un instituto, haciéndose pasar por alumnos, para desarticular una red de narcotráfico. Para Schmidt y Jenko ésta es una gran oportunidad para demostrar lo que valen. El problema es que todo lo que creían saber sobre la adolescencia, el sexo, las drogas y el rock and roll ya ha pasado a la historia: los chicos de hoy no se parecen en nada a los de antes.']
    Dicc_Fox['Las reglas no aplican']=['Domingo', '02:52 PM - 05:14 PM', 'Pelicula', 'Una aspirante a actriz y su chofer luchan contra las manías de su adinerado jefe, Howard Hughes, a la vez que lidian con una atracción que desafía la regla #1 de Hughes: nada de relaciones entre empleados.' ]
    Dicc_Fox['El Hombre Araña 2']=['Domingo', '01:44 AM - 03:07 AM', 'Pelicula', 'El atormentado Peter Parker lucha contra un científico siniestro que utiliza sus tentáculos mecánicos con fines destructivos.']
    General_Canal_Dic["Fox"]=Dicc_Fox

    Dicc_CN={}
    Dicc_CN['Dragon ball super']=['Lunes, Martes, Miercoles, Jueves, Viernes, Sábado', '12:00 AM - 12:25 AM', 'Infantil', 'El dios de la Destrucción ha despertado, y se está dedicando a aniquilar planetas y acaba de descubrir la Tierra. Cuando lo descubre, el guerrero Goku pide ayuda de sus amigos para convertirse en un legendario Super Saiyajin y poder derrotarlo.']
    Dicc_CN['Un_show_más']=['Lunes, Martes, Miercoles, Jueves, Viernes, Sábado',  '12:50 AM - 01:00 AM', 'Infantil', 'Un par de cuidadores de un parque y grandes amigos dejan de lado sus responsabilidades en horas de trabajo para divertirse.']
    Dicc_CN['Escandalosos']=['Lunes, Martes, Miercoles, Jueves, Viernes, Sábado',  '05:00 AM - 06:00 AM', 'Infantil', 'Tres hermanos osos tratan torpemente de encontrar su lugar en una sociedad civilizada, ya sea buscando comida, tratando de hacer amigos humanos o intentando hacerse famosos en Internet.']
    Dicc_CN['El increíble mundo de gumball']=['Lunes, Martes, Miercoles, Jueves, Viernes', '06:15 AM - 06:55 AM', 'Infantil', 'Se cuentan las aventuras de un gato joven llamado Gumball Watterson que tiene una predilección especial por meterse en problemas.']
    Dicc_CN['Ben 10']=['Lunes, Martes, Miercoles, Jueves, Viernes',  '03:45 PM - 04:00 PM', 'Infantil', 'Ben Tennyson es un niño de 10 años de edad que descubre un dispositivo mágico que lo puede convertir en 10 héroes alienígenas diferentes cada uno con sus propias habilidades, ayudando a los demás contra los malhechores.']
    Dicc_CN['Victor y valentino']=['Lunes, Martes, Miercoles, Jueves, Viernes', '04:30 PM - 04:55 PM', 'Infantil', 'Victor y Valentino, dos medio hermanos, pasan el verano con su abuela en Monte Macabre, un pequeño y misterioso pueblo donde los mitos cobran vida.']
    Dicc_CN['Dc super hero girls']=['Sábados, Domingos', '03:00 PM - 03:30 PM', 'Infantil', 'Un grupo de heroínas conviven con la dificultad de superar los problemas y aventuras de la época estudiantil. Además, las elegidas intentan transmitir su confianza y valores al resto de los jóvenes.']
    Dicc_CN['Clarence']=['Lunes, Martes, Miercoles, Jueves, Viernes, Sábado', '12:00 AM - 01:00 AM', 'Infantil', 'Clarence es un niño vivaz y positivo; su perspectiva única de la vida convierte las situaciones mundanas en interesantes y divertidas; el chico comparte sus experiencias y aventuras con su familia y amigos.']
    Dicc_CN['Manzana y Cebollín']=['Sábados, Domingos', '03:00 PM - 03:30 PM', 'Infantil', 'Manzana y Cebolla intentan terminar un cuento antes de que el libro desaparezca para siempre.']
    Dicc_CN['Mao Mao: héroes de puro corazón']=['Lunes, Martes, Miercoles, Jueves, Viernes', '06:55 AM - 07:20 AM', 'Infantil', 'Mao Mao, solitario y explosivo, Colosal, el androide holgazán, y Adorabat, la compañera encantadora, superan sus diferencias y trabajan en equipo para proteger a la población de Valle Puro Corazón del ataque de monstruos y villanos.']
    Dicc_CN['Víctor y Valentino']=['Lunes, Martes, Miercoles, Jueves, Viernes, Sabado, Domingo', '01:30 PM - 01:50 PM', 'Infantil', 'Mientras todo el mundo celebra a Valentino porque le creció su primer vello facial, Vic se pone celoso y recurre a métodos mágicos para dejarse crecer el bigote y competir por la atención.']
    Dicc_CN['El mundo de Craig']=['Lunes, Martes, Miercoles, Jueves, Viernes', '04:00 PM - 04:20 PM', 'Infantil', 'Craig, Kelsey y JP forman equipo con una heroína intergaláctica llamada Cadete Destello, con la esperanza de salvar al Arroyo de la negatividad.']
    Dicc_CN['Mob Psycho 100']=['Sábados, Domingos', '12:25 AM - 12:50 AM', 'Infantil', 'Kageyama Shigeo, apodado "Mob", es un chico con problemas para expresarse pero que en realidad es un poderoso esper. Rodeado por falsos espers, espíritus malignos y misteriosas organizaciones, debrá decidir qué decisión tomar.']
    Dicc_CN['Dr. Stone']=['Lunes, Martes, Miercoles, Jueves, Viernes', '12:26 AM - 12:50 AM', 'Infantil', 'La creación del celular está cada vez más cerca, pero para ello Senku necesitará la ayuda de toda la aldea en la construcción de los materiales necesarios.']
    Dicc_CN['Unikitty']=['Lunes, Martes, Miercoles, Jueves, Viernes', '02:00 AM - 02:48 AM', 'Infantil', 'Cuando Unikitty tiene un pequeño incidente automovilístico con Master Frown, ¡él insiste en llevar el tema a juicio! Frown está encantado: no hay nada peor que un tribunal viejo y aburrido, y está ansioso por someter a Unikitty a esa experiencia']
    Dicc_CN['El show de Tom y Jerry']=['Domingos', '07:15 AM - 07:30 AM', 'Infantil', '¡Acompaña a Tom y Jerry en su nuevo show en el que vivirán nuevas y divertidísimas aventuras mientras pelean por su territorio! Este travieso dúo está listo para volver a la acción con nuevas diabluras, aunque siempre manteniendo la esencia del show original. ¿Los atraparán esta vez?']

    General_Canal_Dic["Cartoon Network"]=Dicc_CN

    Dicc_RCN = {}
    Dicc_RCN['El Chavo animado'] = ['Lunes, Martes, Miércoles, Jueves, Viernes, Sábado, Domingo', '04:50 AM - 07:00 AM', 'Entretenimiento', 'Chavo vive en una vecindad mexicana, junto a sus amigos Popis, Ñoño, Patty y Quico, y vivirá situaciones alocadas en cada episodio.']
    Dicc_RCN['Tacho Pistacho'] = ['Domingo', '07:30 AM - 09:00 AM', 'Entretenimiento', 'La mejor programación para los más pequeños del hogar está en Tacho Pistacho, la señal temática infantil colombiana en donde se puede disfrutar, durante todo el día, de las aventuras de los más queridos personajes.']
    Dicc_RCN['Floricienta'] = ['Sábado, Domingo', '09:00 AM - 10:30 AM', 'Novela', 'Flor es una chica de veinte años que tiene un montón de sueños por cumplir. Su madre ha muerto y ella crece sola, ignorando que su verdadero padre es un importante empresario recientemente muerto. Para sobrevivir se ve obligada a alternar diferentes trabajos. Hasta que, por encontrar un lugar donde vivir, acepta ser la institutriz en la casa de los Fritzenwalden, en donde logrará ganarse el cariño de los más chicos, quienes encontrarán en ella la alegría perdida por una rígida educación.']
    Dicc_RCN['Chica vampiro'] = ['Domingo', '10:30 AM - 12:30 PM', 'Entretenimiento', 'A punto de cumplir 16 años, Daisy, una chica humana, lleva una vida normal, con una familia bastante particular: sus padres son vampiros. Sin embargo, todo cambia cuando Daisy sufre un terrible accidente que sitúa a sus padres ante un gran dilema: dejar morir a su pequeña o morderla para salvarle la vida, concediéndole así la inmortalidad.']
    Dicc_RCN['Noticias RCN'] = ['Lunes, Martes, Miércoles, Jueves, Viernes, Sábado, Domingo', '07:00 PM - 08:00 PM', 'Informativo', 'Presenta una cobertura especial de los sucesos nacionales e internacionales más impactantes, todo a través de entrevistas, opiniones, debates y análisis con los protagonistas de la realidad.']
    Dicc_RCN['Nuestro cine'] = ['Sábado, Domingo', '03:00 PM - 05:00 PM', 'Pelicula', 'Se presentan peliculas variadas de categoría familiar']
    Dicc_RCN['Francisco, el matemático'] = ['Domingo', '06:00 PM - 07:00 PM', 'Novela', 'Un profesor de matemáticas debe enfrentarse a las actitudes rebeldes de algunos estudiantes del colegio en el que es contratado.']
    Dicc_RCN['Chepe fortuna'] = ['Lunes, Domingo', '08:00 PM - 10:00 PM', 'Novela', 'Chepe Fortuna es un pescador y líder del barrio "El Tiburón", y sueña con ser alcalde para sacar a su gente de la pobreza y asegurarle un mejor futuro. Por su parte, Niña Cabrales, descendiente de una de las familias más importantes de la costa colombiana, regresa de España con la intención de llevar adelante varios proyectos ecológicos, además de ayudar a los pescadores de "El Tiburón". A pesar de que estos dos personajes no se conocen personalmente, ambos soñarán el uno con el otro y protagonizarán una historia de amor.']
    Dicc_RCN['Yo, José Gabriel inolvidable'] = ['Domingo', '10:00 PM - 11:00 PM', 'Entretenimiento', 'Aunque queremos estar en el estudio, debemos quedarnos en casa, pero hemos preparado un programa muy especial de José Gabriel con tres grandes invitados de lujo.']
    Dicc_RCN['Efecto Naím'] = ['Lunes, Martes, Miércoles, Jueves, Viernes, Sábado, Domingo', '11:00 PM - 11:30 PM', 'Informativo', 'Un espacio de análisis político a nivel global que, mediante entrevistas e informes, ofrece la información más certera, veraz y objetiva que expone las sorpresas del poder. Esta edición, cuenta con corresponsales en varios puntos claves del mundo.']
    Dicc_RCN['Hugo Chávez, el comandante'] = ['Lunes, Martes, Miércoles, Jueves, Viernes, Sábado, Domingo', '12:40 AM - 01:20 AM', 'Novela', 'En el camino hacia el poder, se cosechan amores y odios. Esta serie explorará la presidencia del venezolano Hugo Chávez y sus aspectos más controvertidos, desde su tensa rivalidad con Estados Unidos, su amistad con el líder cubano Fidel Castro y su compleja relación con la prensa y el sector privado.']
    Dicc_RCN['El mundo del campo'] = ['Lunes, Martes, Miércoles, Jueves, Viernes, Sábado, Domingo', '04:10 AM - 04:50 AM', 'Informativo', 'Presenta un completo recorrido por el campo colombiano y de muchos otros países, siempre buscando las cosas buenas que hace la gente de la región y sacando adelante la actividad agropecuaria realizada en cada zona.']
    Dicc_RCN['Historias clasificadas'] = ['Lunes', '10:50 PM - 11:30 PM', 'Informativo', 'Avisos clasificados curiosos, extraños, divertidos y sorprendentes en donde, detrás de cada uno, hay una historia para contar de personas comunes que se han visto obligadas a poner uno en el diario para solucionar sus problemas económicos, sentimentales, laborales o familiares.']
    Dicc_RCN['Anónima'] = ['Lunes, Martes, Miércoles, Jueves, Viernes', '12:50 AM - 01:30 AM', 'Novela', 'Después de pasar 10 años en la cárcel, Victoria sale del presidio con un único anhelo: tener una vida normal. Pero su pasado, aquel del que se quiere olvidar definitivamente, da un inesperado giro que la lleva a ser madre a la fuerza de un niño que no es suyo.'] 
    Dicc_RCN['Allá te espero'] = ['Lunes, Martes, Miércoles, Jueves, Viernes', '01:00 AM - 02:00 AM', 'Novela', 'Rosa María y David no tienen mucho en común: ella es muy latina y él Colombiano-Americano. Mientras para Rosa María la familia es lo primero, para David la vida se sintetiza en trabajar y hacer dinero. Difícilmente estas dos personas podrían enamorarse, pero por distintas razones, ambos llegan en contra de su voluntad a vivir en la misma ciudad y sus vidas comienzan a cambiar radicalmente hasta unirlos en medio de la soledad y la decepción en las que los dejaron sus respectivas parejas; la de David, porque no pudo adaptarse al país de donde sus papás emigraron años atrás, y la de Rosa María, porque su sueño era vivir en los Estados Unidos ganando en dólares para salir de la mala situación económica por la que estaban atravesando.']
    Dicc_RCN['La rosa de Guadalupe'] = ['Lunes, Martes, Miércoles, Jueves, Viernes', '04:30 PM - 07:00 PM', 'Novela', 'La Rosa de Guadalupe es una serie de televisión Mexicana transmitida por el Canal RCN, que relata una serie de historias donde la protagonista es la Virgen de Guadalupe y sus milagros que se manifiestan con una rosa blanca. En cada capitulo hay una historia nueva con diferentes conflictos y de basan en problemas de la sociedad como el bullying, el engaño, las mentiras, la traición, la violencia, drogadicción y más. Hacia el final de cada capítulo el personaje principal encuentra una solución a su problema siempre dejando una moraleja.']
    Dicc_RCN['Soy tu dueña'] = ['Lunes, Martes, Miércoles, Jueves, Viernes', '02:30 PM - 03:30 PM', 'Novela', 'Alonso Peñalvert engaña a Valentina Villalba con la cuñada de ella, dejándola plantada en el altar. Tras este hecho, la mujer herida dirá que ningún hombre volverá a jugar con ella y se va a vivir a una de sus haciendas, donde se encuentra José Miguel Montesinos, con quien nacerá un amor, pero ella no cederá. Todo se complica con la llegada de Ivana, su cuñada, a la finca y el regreso de Alonso, dispuesto a conquistarla nuevamente. La traicionera y sus cómplices se encargarán de hacer imposible la vida de Valentina y separarla de José.']
    Dicc_RCN['Betty, la fea'] = ['Lunes, Martes, Miércoles, Jueves, Viernes', '08:00 PM - 10:00 PM', 'Novela', 'Betty era una mujer que estaba acostumbrada a la idea de quedarse solterona, una joven poco agraciada que nadie invitaba a salir y que se conformaba con el recuerdo tormentoso de un novio que la dejó a los pocos días. Ella vivía para sacar las mejores notas de la universidad, para hacer cursos y posgrados y con esto hacer feliz a su padre, quien se siente muy orgulloso de su hija.']
    Dicc_RCN['La hija del Mariachi'] = ['Lunes, Martes, Miércoles, Jueves, Viernes', '10:00 PM - 11:00 PM', 'Novela', 'La noche que Rosario ve a Emiliano en las puertas del bar, con huellas de haber sido atracado, decide ayudarlo sin saber que es un acaudalado joven que ha llegado a Bogotá huyendo de la justicia por un delito que no cometió.']
    Dicc_RCN['Te doy la vida'] = ['Lunes, Martes, Miércoles, Jueves, Viernes', ' 03:30 PM - 04:30 PM', 'Novela', 'Fabián Gararrido es un mecánico de barrio cuya rutina se ha basado en cuidar a su familia y a su pareja Yoana, con quien planea no tener hijos hasta que puedan casarse. Su vida cambia por completo cuando se entera de que es el papá de un pequeño que fue diagnosticado con leucemia, pues, en sus deseos de ayudarlo, logra crear un vínculo especial tanto con él como con su madre Isadora, quien llega para acariciar lo más profundo de su corazón.']
    Dicc_RCN['Clásico RCN Andina'] = ['Sábado', '10:30 AM - 12:30 PM', 'Entretenimiento', 'Carrera ciclística profesional por etapas que se disputa anualmente en Colombia y es organizada por la Federación Colombiana de Ciclismo.']
    Dicc_RCN['El Joé'] = ['Sábado', '08:00 PM - 10:00 PM', 'Novela', 'La vida del cantante y compositor cartagenero Álvaro José Arroyo González, más conocido como El Joe Arroyo, uno de los más grandes íconos de la música colombiana.']
    Dicc_RCN['Show de las estrellas'] = ['Sábado', '10:00 PM - 12:00 AM', 'Entretenimiento', 'Espacio musical de la televisión colombiana, producido, presentado y dirigido por el popular animador Jorge Barón.']
        
    General_Canal_Dic["RCN"]=Dicc_RCN

    #Agrega Los Horarios De Caracol Extraidos De La Web

    urlxddd="https://www.caracoltv.com/programacion"

    pageCar=urlopen(urlxddd)
    htmlCar=pageCar.read().decode("utf-8")
    soupCar = BeautifulSoup(htmlCar, "html.parser")
    textoCar = (soupCar.get_text()).split("\n")
    lineas = [linea.strip() for linea in textoCar if linea != '']

    for i in range(len(lineas)):
      if lineas[i] == "Lunes":
        lineas = lineas[i:]
        break
    lineasDef=[]
    for elementos in lineas:
      if elementos == '' or elementos == 'cc' or elementos == 'Programación' or elementos == 'Descripción' : continue
      else:lineasDef.append(elementos)

    revisiondias,Dicc_Caracol="",{}
    for elemento in range(len(lineasDef)):
      if lineasDef[elemento]=="Publicidad": break
      elif lineasDef[elemento]=="Lunes" or lineasDef[elemento]=="Martes" or lineasDef[elemento]=="Miércoles" or lineasDef[elemento]=="Jueves"or lineasDef[elemento]=="Viernes" or lineasDef[elemento]=="Sábado" or lineasDef[elemento]=="Domingo": revisiondias=lineasDef[elemento]
      elif "AM" in lineasDef[elemento] or "PM" in lineasDef[elemento]:
        lineasDef.pop(elemento)
        compr=Dicc_Caracol.get(lineasDef[elemento+1],"B)")
        if compr!="B)":
          if revisiondias in Dicc_Caracol[lineasDef[elemento+1]][0]:continue
          else: Dicc_Caracol[lineasDef[elemento+1]]=[(Dicc_Caracol[lineasDef[elemento+1]][0]+", " + revisiondias),Dicc_Caracol[lineasDef[elemento+1]][1]]
        else: Dicc_Caracol[lineasDef[elemento+1]]=[revisiondias,lineasDef[elemento]]
    for programa in ProgramasCaracolDeleteados:
      pru=Dicc_Caracol.get(programa,False)
      if pru!=False: del Dicc_Caracol[programa]
    for programa in Dicc_Caracol:
      Dicc_Caracol[programa]+=[ListaCar[programa][0],ListaCar[programa][1]]

    General_Canal_Dic["Caracol"]=Dicc_Caracol
    
    Escribir_Archivo_Con_Indices(General_Canal_Dic,Dicc_Fox,Dicc_CN,Dicc_Caracol,Dicc_RCN)
    
    
def Escribir_Archivo_Con_Indices(General_Canal_Dic,Dicc_Fox,Dicc_CN,Dicc_Caracol,Dicc_RCN):
    
    #Codigo para escribir el archivo codificado *=Canal, $=Programa, +=Dia, #=Hora, &=Categoría, /= Resumen "
    
    codificado=open("ProgramacionChanels.txt","w")
    for canal in General_Canal_Dic:
        codificado.write("*"+canal+"\n")
        if canal=="Fox":
          for programa in Dicc_Fox:
            codificado.write("$"+str(programa)+"\n")
            codificado.write(("+"+str(Dicc_Fox[programa][0]))+"\n")
            codificado.write("#"+str(Dicc_Fox[programa][1])+"\n")
            codificado.write("&"+str(Dicc_Fox[programa][2])+"\n")
            codificado.write("/"+str(Dicc_Fox[programa][3])+"\n")
        elif canal=="Cartoon Network":
          for programa in Dicc_CN:
            codificado.write("$"+str(programa)+"\n")
            codificado.write(("+"+str(Dicc_CN[programa][0]))+"\n")
            codificado.write("#"+str(Dicc_CN[programa][1])+"\n")
            codificado.write("&"+str(Dicc_CN[programa][2])+"\n")
            codificado.write("/"+str(Dicc_CN[programa][3])+"\n")
        elif canal=="Caracol":
          for programa in Dicc_Caracol:
            codificado.write("$"+str(programa)+"\n")
            codificado.write(("+"+str(Dicc_Caracol[programa][0]))+"\n")
            codificado.write("#"+str(Dicc_Caracol[programa][1])+"\n")
            codificado.write("&"+str(Dicc_Caracol[programa][2])+"\n")
            codificado.write("/"+str(Dicc_Caracol[programa][3])+"\n")
        elif canal=="RCN":
          for programa in Dicc_RCN:
            codificado.write("$"+str(programa)+"\n")
            codificado.write(("+"+str(Dicc_RCN[programa][0]))+"\n")
            codificado.write("#"+str(Dicc_RCN[programa][1])+"\n")
            codificado.write("&"+str(Dicc_RCN[programa][2])+"\n")
            codificado.write("/"+str(Dicc_RCN[programa][3])+"\n")

    codificado.close()
main()
